services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile.dev
    ports:
      - "18001:80" # expose nginx sur le port 80
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod