version: '3'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "8080:80" # expose nginx sur le port 80
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod