package com.ares_expedition.enums.game;

public enum EventStateTypeEnum {
    OCEAN_FLIPPED,
    PHASE_BUILDER_DEVELOPMENT_LOCKED,
    PHASE_BUILDER_CONSTRUCTION_LOCKED,
    CARD_ACTIVATOR,
    DRAW_CARDS,
    PRODUCTION_CARDS,
    DISCARD,
    RESEARCH_CARDS_QUERIED,
    SCAN_KEEP_QUERIED,
    SCAN_KEEP_UNQUERIED,
    TARGET_CARD_ADD_RESSOURCE,
    SPECIAL_BUILDER,
    DRAW_CARDS_UNQUERIED,
    ADD_PRODUCTION,
    INCREASE_RESEARCH_SCANKEEP,
    UPGRADE_PHASE,
    ADD_RESSOURCE_TO_PLAYER,
    DRAW_THEN_DISCARD_UNQUERIED
}
