export type EventTitleKey = 'phasePlanification' | 'phaseDevelopment' | 'phaseConstruction' | 'phaseAction' | 'phaseProduction' | 'phaseResearch' | 'phaseCardUpgrade'
| 'builderConscription' | 'builderMaiNi' | 'builderWorkCrews' | 'builderAssetLiquidation' | 'builderGreen9MCFree' | 'builderAssortedEnterprises' | 'builderSelfReplicatingBacteria'
| 'eventInitialDraft' | 'eventInitialDraftThenCorp' | 'eventCorpSelection' | 'eventCorpSelectionMerger'
| 'eventOptionalSell' | 'eventForcedSell'
export type GameOptionKey = 'discovery' |  'standardProjectUpgrade' | 'additionalAwards'
| 'foundations' | 'infrastructureMandatory'
| 'promoCards' | 'fanmadeCards' | 'balancedCards'
| 'initialDraft' | 'merger' | 'deadHand'
| 'moon' | 'moonMandatory'
export type InterfaceTitleKey = 'createGame' | 'createGamePlayers' | 'createGameOptions' | 'createGamePlayerNumber' | 'createGameAdditionalContent' | 'createGameAdditionalCards' | 'createGameGameMode'
| 'cardOverviewTitle'
| 'newGameLinkPlayerLaunchSite' | 'newGameLinkTitle' | 'newGameLinkGameOptions'
export type ButtonCaptionKey = 'buttonCreateGameCreate' | 'buttonCreateGameEnableAll' | 'buttonCreateGameDisableAll' |
'buttonHomeNewGame' | 'buttonHomeCardOverview' | 'buttonHomeDiscord' | 'buttonHomeBuyAres' | 'buttonHomeStats'
| 'buttonCardOverviewDisplayBalanced' | 'buttonCardOverviewDisplayAll'
export type ErrorKey = 'errorCreateGameNameAndColor' | 'errorCreateGameNameServerOffline' | 'errorCreateGameNameOtherError'
