# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI build and test

on:
  push:
    branches-ignore: "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /front

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'
    
    - name: Install front dependencies
      run: npm ci
      working-directory: front

    - name: Run front tests
      run: npm run test:ci
      working-directory: front
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push front image
      uses: docker/build-push-action@v5
      with: 
        context: ./front
        push: true
        tags: ${{ secret.DOCKER_USERNAME }}/front:latest
      
    - name: Build and push back image
      uses: docker/build-push-action@v5
      with:
        context: ./back
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/back:latest

#    - name: Run build
#      run: npm run build --if-present
#      working-directory: front
